""" Script to create fields mapping from field list from CSV """
FIELDS_NL = (
	'Activiteits-ID',
	'Datum van activiteit',
	'Naam activiteit',
	'Activiteitstype',
	'Beschrijving van activiteit',
	'Verstreken tijd',
	'Afstand',
	'Max. hartslag',
	'Vergelijkbare poging',
	'Woon-werkverkeer',
	'Privénotitie activiteit',
	'Uitrusting voor activiteit',
	'Bestandsnaam',
	'Gewicht sporter',
	'Gewicht fiets',
	'Verstreken tijd',
	'Beweegtijd',
	'Afstand',
	'Max. snelheid',
	'Gemiddelde snelheid',
	'Totale stijging',
	'Totale daling',
	'Kleinste hoogte',
	'Grootste hoogte',
	'Max. stijgingspercentage',
	'Gemiddeld stijgingspercentage',
	'Gemiddeld positief stijgingspercentage',
	'Gemiddeld negatief stijgingspercentage',
	'Max. cadans',
	'Gemiddelde cadans',
	'Max. hartslag',
	'Gemiddelde hartslag',
	'Maximaal wattage',
	'Gemiddeld wattage',
	'Calorieën',
	'Maximale temperatuur',
	'Gemiddelde temperatuur',
	'Vergelijkbare poging',
	'Totale arbeid',
	'Aantal hardloopsessies',
	'Tijd bergop',
	'Tijd bergaf',
	'Andere tijd',
	'Ervaren inspanning',
	'Type',
	'Starttijd',
	'Gewogen gemiddeld vermogen',
	'Aantal vermogensgegevens',
	'Voorkeur voor ervaren inspanning',
	'Ervaren vergelijkbare poging',
	'Woon-werkverkeer',
	'Totaal geheven gewicht',
	'Van upload',
	'Aan stijgingspercentage aangepaste afstand',
	'Tijd weerbeeld',
	'Weersomstandigheden',
	'Buitentemperatuur',
	'Gevoelstemperatuur',
	'Dauwpunt',
	'Vochtigheid',
	'Luchtdruk',
	'Windsnelheid',
	'Windstoot',
	'Windrichting',
	'Neerslagintensiteit',
	'Tijd zonsopgang',
	'Tijd zonsondergang',
	'Maanstand',
	'Fiets',
	'Uitrusting',
	'Kans op neerslag',
	'Type neerslag',
	'Bewolking',
	'Zicht',
	'UV-index',
	'Ozonwaarde',
	'Aantal jumps',
	'Totale grit',
	'Gemiddelde flow',
	'Gemeld',
	'Gemiddelde snelheid (op basis van verstreken tijd)',
	'Afstand (onverharde wegen)',
	'Afstand nieuw ontdekte wegen',
	'Afstand op nieuw ontdekte wegen (onverhard)',
	'Aantal activiteiten',
	'Totaal aantal stappen',
	'CO2-besparing',
	'Lengte van zwembad',
	'Trainingsbelasting',
	'Intensiteit',
	'Gemiddelde vergelijkbare tempo op vlak terrein',
	'Tijd op de timer',
	'Totaalaantal cycli',
	'Media',
)

import dataclasses
from bast1aan.strava_reader.entities import Activity
activity_fields = tuple(field.name for field in dataclasses.fields(Activity))
field_mapping_nl = dict(zip(FIELDS_NL, activity_fields))
print(field_mapping_nl)
